In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

# Import our input dataset
diabetes_df = pd.read_csv('./Resources/diabetes.csv')
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
# Remove diabetes outcome target from features data
y = diabetes_df.Outcome
X = diabetes_df.drop(columns="Outcome")

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [4]:
# Preprocess numerical data for neural network

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [5]:
# Define the logistic regression model
log_classifier = LogisticRegression(solver="lbfgs",max_iter=200)

# Train the model
log_classifier.fit(X_train,y_train)

# Evaluate the model
y_pred = log_classifier.predict(X_test)
print(f" Logistic regression model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Logistic regression model accuracy: 0.729

In [6]:
# Define the basic neural network model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=8))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
18/18 [==============================] - 1s 2ms/step - loss: 0.8874 - accuracy: 0.3542
Epoch 2/50
18/18 [==============================] - 0s 2ms/step - loss: 0.8186 - accuracy: 0.3663
Epoch 3/50
18/18 [==============================] - 0s 2ms/step - loss: 0.7625 - accuracy: 0.4271
Epoch 4/50
18/18 [==============================] - 0s 2ms/step - loss: 0.7187 - accuracy: 0.4983
Epoch 5/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6808 - accuracy: 0.5781
Epoch 6/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6504 - accuracy: 0.6615
Epoch 7/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6253 - accuracy: 0.7170
Epoch 8/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6039 - accuracy: 0.7517
Epoch 9/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5846 - accuracy: 0.7587
Epoch 10/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5686 - accuracy: 0.7622
Epoch 11/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5541 - accuracy: 0.7656
Epoch 12/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5425 - accuracy: 0.7691
Epoch 13/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5309 - accuracy: 0.7795
Epoch 14/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5215 - accuracy: 0.7865
Epoch 15/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5123 - accuracy: 0.7847
Epoch 16/50
18/18 [==============================] - 0s 2ms/step - loss: 0.5048 - accuracy: 0.7865
Epoch 17/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4982 - accuracy: 0.7882
Epoch 18/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4924 - accuracy: 0.7899
Epoch 19/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4875 - accuracy: 0.7899
Epoch 20/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4828 - accuracy: 0.7917
Epoch 21/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4791 - accuracy: 0.7917
Epoch 22/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4758 - accuracy: 0.7882
Epoch 23/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4723 - accuracy: 0.7917
Epoch 24/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4696 - accuracy: 0.7934
Epoch 25/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4668 - accuracy: 0.7934
Epoch 26/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4649 - accuracy: 0.7917
Epoch 27/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4627 - accuracy: 0.7934
Epoch 28/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4612 - accuracy: 0.7917
Epoch 29/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4592 - accuracy: 0.7934
Epoch 30/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4579 - accuracy: 0.7934
Epoch 31/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4565 - accuracy: 0.7899
Epoch 32/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4553 - accuracy: 0.7951
Epoch 33/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4543 - accuracy: 0.7899
Epoch 34/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4529 - accuracy: 0.7917
Epoch 35/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4523 - accuracy: 0.7917
Epoch 36/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4509 - accuracy: 0.7951
Epoch 37/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4503 - accuracy: 0.7934
Epoch 38/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.7934
Epoch 39/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4481 - accuracy: 0.7969
Epoch 40/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.7951
Epoch 41/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4466 - accuracy: 0.7986
Epoch 42/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4462 - accuracy: 0.7969
Epoch 43/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4450 - accuracy: 0.7951
Epoch 44/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4449 - accuracy: 0.7934
Epoch 45/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4438 - accuracy: 0.7934
Epoch 46/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4434 - accuracy: 0.7917
Epoch 47/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4425 - accuracy: 0.7899
Epoch 48/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4420 - accuracy: 0.7917
Epoch 49/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4414 - accuracy: 0.7934
Epoch 50/50
18/18 [==============================] - 0s 2ms/step - loss: 0.4408 - accuracy: 0.7934
6/6 - 0s - loss: 0.5019 - accuracy: 0.7344 - 189ms/epoch - 31ms/step
Loss: 0.501895010471344, Accuracy: 0.734375

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

# Import our input dataset
tele_df = pd.read_csv('./Resources/bank_telemarketing.csv')
tele_df.head()

,Age,Job,Marital_Status,Education,Default_Credit,Housing_Loan,Personal_Loan,Subscribed
0,56,other,married,Primary_Education,no,no,no,no
1,37,services,married,Secondary_Education,no,yes,no,no
2,40,admin,married,Primary_Education,no,no,no,no
3,56,services,married,Secondary_Education,no,no,yes,no
4,59,admin,married,Professional_Education,no,no,no,no

In [8]:
# Generate our categorical variable list
tele_cat = tele_df.dtypes[tele_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
tele_df[tele_cat].nunique()

Job               9
Marital_Status    3
Education         4
Default_Credit    2
Housing_Loan      2
Personal_Loan     2
Subscribed        2
dtype: int64

In [9]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(tele_df[tele_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(tele_cat)
encode_df.head()

/Users/jules/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,Marital_Status_divorced,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [10]:
# Merge one-hot encoded features and drop the originals
tele_df = tele_df.merge(encode_df,left_index=True, right_index=True)
tele_df = tele_df.drop(tele_cat,1)
tele_df.head()

/var/folders/3g/z4d2rf150855241yq7jlg2yh0000gn/T/ipykernel_45946/2291554867.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  tele_df = tele_df.drop(tele_cat,1)

,Age,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,56,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,40,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,59,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [11]:
# Remove loan status target from features data
y = tele_df.Subscribed_yes.values
X = tele_df.drop(columns=["Subscribed_no","Subscribed_yes"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Create the SVM model
svm = SVC(kernel='linear')

In [15]:
# Train the model
svm.fit(X_train, y_train)

SVC(kernel='linear')

In [16]:
# Evaluate the model
y_pred = svm.predict(X_test_scaled)
print(f" SVM model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 SVM model accuracy: 0.873

In [17]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
715/715 [==============================] - 2s 2ms/step - loss: 0.4624 - accuracy: 0.8249
Epoch 2/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3721 - accuracy: 0.8728
Epoch 3/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3700 - accuracy: 0.8734
Epoch 4/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3684 - accuracy: 0.8735
Epoch 5/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3677 - accuracy: 0.8733
Epoch 6/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3668 - accuracy: 0.8730
Epoch 7/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3665 - accuracy: 0.8734
Epoch 8/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3661 - accuracy: 0.8736
Epoch 9/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3658 - accuracy: 0.8737
Epoch 10/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3657 - accuracy: 0.8733
Epoch 11/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3655 - accuracy: 0.8736
Epoch 12/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3651 - accuracy: 0.8737
Epoch 13/50
715/715 [==============================] - 2s 2ms/step - loss: 0.3652 - accuracy: 0.8735
Epoch 14/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3649 - accuracy: 0.8739
Epoch 15/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3646 - accuracy: 0.8735
Epoch 16/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3643 - accuracy: 0.8738
Epoch 17/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3644 - accuracy: 0.8736
Epoch 18/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3642 - accuracy: 0.8736
Epoch 19/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3641 - accuracy: 0.8739
Epoch 20/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3640 - accuracy: 0.8738
Epoch 21/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3640 - accuracy: 0.8739
Epoch 22/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3636 - accuracy: 0.8737
Epoch 23/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3636 - accuracy: 0.8737
Epoch 24/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3634 - accuracy: 0.8738
Epoch 25/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3633 - accuracy: 0.8735
Epoch 26/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3632 - accuracy: 0.8738
Epoch 27/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3632 - accuracy: 0.8740
Epoch 28/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3632 - accuracy: 0.8738
Epoch 29/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3631 - accuracy: 0.8737
Epoch 30/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8739
Epoch 31/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3628 - accuracy: 0.8734
Epoch 32/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3628 - accuracy: 0.8739
Epoch 33/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3629 - accuracy: 0.8735
Epoch 34/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3625 - accuracy: 0.8736
Epoch 35/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3627 - accuracy: 0.8737
Epoch 36/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3624 - accuracy: 0.8740
Epoch 37/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3625 - accuracy: 0.8739
Epoch 38/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3625 - accuracy: 0.8735
Epoch 39/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3623 - accuracy: 0.8741
Epoch 40/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3623 - accuracy: 0.8735
Epoch 41/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3622 - accuracy: 0.8737
Epoch 42/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3620 - accuracy: 0.8737
Epoch 43/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3622 - accuracy: 0.8740
Epoch 44/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3621 - accuracy: 0.8736
Epoch 45/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3621 - accuracy: 0.8732
Epoch 46/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3619 - accuracy: 0.8739
Epoch 47/50
715/715 [==============================] - 1s 1ms/step - loss: 0.3620 - accuracy: 0.8736
Epoch 48/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8736
Epoch 49/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8737
Epoch 50/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3617 - accuracy: 0.8738
239/239 - 0s - loss: 0.3692 - accuracy: 0.8734 - 427ms/epoch - 2ms/step
Loss: 0.36923331022262573, Accuracy: 0.8733595609664917